schema_version: 1

context:
  name: rabbitpy
  version: "3.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rabbitpy-${{ version }}.tar.gz
  sha256: 9322a1e82b4d3d1afc21a617ce0b1e86b921174328735e7d54abc9525805ae5c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - setuptools
  run:
    - python >=${{ python_min }}
    - pamqp >=4,<5

tests:
  - python:
      imports:
        - rabbitpy
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: A pure python, thread-safe, minimalistic and pythonic RabbitMQ client library
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://gmr.github.io/rabbitpy/

extra:
  recipe-maintainers:
    - akrherz
